name: UPDATE

# Controls when the action will run. 
on: [issues, issue_comment]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clone:
    name: Roc Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        env:
          GITHUB_LOGIN: Roc-zhou
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GITHUB_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@github.com:Roc-zhou/Roc-zhou.git
          cd Roc-zhou
          chmod 777 app
          ./app
          git config user.name 'Roc-zhou'
          git config user.email 'roc.zhousir@gmaol.com'
          git checkout main
          git add .
          git commit -m "Update from Github Action"
          git push origin main

      - name: Done
        run: echo 'done'
